# Generated by Django 2.2.10 on 2020-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The given name. Only A-Z are acceptable.', max_length=30, verbose_name='first name'),
        ),
    ]
