version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE:      docker
      MYSQL_USER:          docker
      MYSQL_PASSWORD:      docker
    volumes:
      - storage:/var/lib/mysql
      - ../docker/mysql:/etc/mysql/conf.d
  web:
    build: ./django-uwsgi-nginx
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER:     docker
      MYSQL_PASSWORD: docker
      MYSQL_HOST:     db
      VIRTUAL_HOST: app.www-mmde.ist.osaka-u.ac.jp
      VIRTUAL_PORT: '8080'
    volumes:
      - ../src:/code/app
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: $DIR_PUBZ_STORAGE
      o: bind