version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER:     $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - storage:/var/lib/mysql
      - ../docker/mysql:/etc/mysql/conf.d
  web:
    build: ./django-uwsgi-nginx
    environment:
      MYSQL_DATABASE: $MYSQL_ROOT_PASSWORD
      MYSQL_USER:     $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST:     db
    volumes:
      - ../src:/code/app
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../storage/db/data/
      o: bind