FROM python:3.7
MAINTAINER Yoshimura Naoya <yoshimura708x@gmail.com>

ENV PYTHONUNBUFFERED 1
ENV PROJECT_ROOT /code
RUN mkdir $PROJECT_ROOT
WORKDIR $PROJECT_ROOT

COPY requirements.txt requirements.txt

# Install MySQL Client&Python Driver, pip
RUN apt-get update
RUN apt-get install -y mysql-client
RUN pip3 install PyMySQL
RUN pip3 install -r requirements.txt

# Run
COPY ./  ./
CMD python3 ./app/manage.py runserver 0.0.0.0:8000
