# Generated by Django 2.2 on 2020-02-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=128)),
                ('name_ja', models.CharField(blank=True, max_length=128, null=True)),
                ('dep_en', models.TextField(blank=True, null=True)),
                ('dep_ja', models.TextField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_join', models.DateField(blank=True, null=True)),
                ('date_leave', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bibtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('JA', 'Japanese')], max_length=2)),
                ('title_en', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('title_ja', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('bib_type', models.CharField(choices=[('AWARD', 'Award'), ('KEYNOTE', 'Keynote'), ('SAMEASBOOK', 'Same as the Book')], default='SAMEASBOOK', max_length=32)),
                ('book_title', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('volume', models.CharField(blank=True, max_length=128, null=True)),
                ('number', models.CharField(blank=True, max_length=128, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=32, null=True)),
                ('edition', models.TextField(blank=True, max_length=16, null=True)),
                ('pub_date', models.DateField(blank=True, default='1970-01-01', null=True)),
                ('use_date_info', models.BooleanField(blank=True, default=False)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=32)),
                ('priority', models.CharField(choices=[('0', 'Default'), ('5', 'High'), ('9', 'Super High')], default='0', max_length=1)),
                ('abstruct', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='api')),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abbr', models.CharField(blank=True, default='', max_length=256)),
                ('style', models.CharField(choices=[('ARTICLE', (('JOURNAL', 'Journal'),)), ('INPROCEEDINGS', (('INPROCEEDINGS', 'in Proceedings'), ('CONF_DOMESTIC', '国内会議'), ('CONF_DOMESTIC_NO_REVIEW', '国内研究会'), ('CONF_NATIONAL', '全国大会'))), ('BOOK', (('BOOK', 'Book'), ('NEWS', 'News Paper'), ('TECHREPORT', 'Tech Report'))), ('Removed in the future', (('INTPROC', "Int'l Proc."), ('KEYNOTE', '[Warning!]Keynote'), ('AWARD', '[Warning!]Award'))), ('Othres', (('MISC', 'Others'), ('ARTICLE', 'Article'), ('INBOOK', 'in Book'), ('BOOKLET', 'Booklet'), ('INCOLLECTION', 'in Collection'), ('MANUAL', 'Manual'), ('MASTERTHESIS', 'Master Thesis'), ('PHDTHESIS', 'Ph.D Thesis'), ('PROCEEDINGS', 'Proceedings'), ('UNPUBLISHED', 'Unpublished')))], max_length=32)),
                ('institution', models.CharField(blank=True, max_length=256, null=True)),
                ('organizer', models.CharField(blank=True, max_length=256, null=True)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bibtex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bibtex')),
            ],
        ),
    ]
