# Generated by Django 2.2 on 2020-02-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200223_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibtex',
            name='acceptance_rate',
        ),
        migrations.RemoveField(
            model_name='bibtex',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bibtex',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='bibtex',
            name='priority',
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='pub_date',
            field=models.DateField(blank=True, default='2010-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='style',
            field=models.CharField(choices=[('ARTICLE', (('JOURNAL', 'Journal'),)), ('INPROCEEDINGS', (('INPROCEEDINGS', 'Internatinal Conference'), ('CONF_DOMESTIC', 'Domestic Conference'))), ('BOOK', (('BOOK', 'Book'), ('NEWS', 'News Paper'))), ('Othres', (('MISC', 'Others'), ('ARTICLE', 'Article')))], max_length=32),
        ),
    ]
