# Generated by Django 2.2 on 2020-02-24 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200223_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='address',
        ),
        migrations.RemoveField(
            model_name='book',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='book',
            name='organizer',
        ),
        migrations.AddField(
            model_name='bibtex',
            name='doi',
            field=models.CharField(blank=True, default='', help_text='Digital Object Identifier.(len=128, optional)', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime which this object is created.This column is automatically filled by django app.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_join',
            field=models.DateField(blank=True, help_text='Date which this poerson joinded this department.(null=True, blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_leave',
            field=models.DateField(blank=True, help_text='Date which this poerson leave this department.(null=True, blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='dep_en',
            field=models.TextField(blank=True, help_text='Depertment information (in English).(null=True, blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='dep_ja',
            field=models.TextField(blank=True, help_text='Depertment Information (Japanese).(null=True, blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.EmailField(blank=True, help_text='E-mail address.(null=True, blank=True)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Datetime which this object is edited last time.This column is automatically filled by django app.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.CharField(help_text='Full Name (in English). First name and family name should be split by space.See validation rules. (len=128).', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ja',
            field=models.CharField(blank=True, help_text='Full Name (Japanese). First name and family name should be split by space.See validation rules.  (len=128, null=True, blank=True)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='owner',
            field=models.ForeignKey(help_text='User who creates this object.This column is automatically filled by django app.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authororder',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='a order of this author within the bibtex.For example, this author is a first author, set 1.(Only positive integer is acceptable)'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='abstruct',
            field=models.TextField(blank=True, help_text='abstract of the paper.(blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='authors',
            field=models.ManyToManyField(help_text="authors of this publication. The order is stored in ``AuthorOrder`` model.(model='Author', through='AuthorOrder').", through='core.AuthorOrder', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='bib_type',
            field=models.CharField(choices=[('AWARD', 'Award'), ('KEYNOTE', 'Keynote'), ('SAMEASBOOK', 'Same as the Book')], default='SAMEASBOOK', help_text='If this entry is related to an award or a presentation (not article),set this field.(choose from ``BIBSTYLE_CHOICES``, see note for available choices.)', max_length=32),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='book',
            field=models.ForeignKey(help_text='book title including details (e.g. year). (len=512, null=True, blank=True)', on_delete=django.db.models.deletion.PROTECT, to='core.Book'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='book_title',
            field=models.CharField(blank=True, default='', help_text='The title of the book including details (e.g. year).(len=512, null=True, blank=True)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='chapter',
            field=models.CharField(blank=True, help_text='chapter number (章). Before published, ignore this column. (len=128, blank=True)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time which this record is created.This column is automatically filled by django app.(auto_add_now=True)'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='edition',
            field=models.CharField(blank=True, help_text='edition (版). Before published or no longer needed to the format of the publication, ignore this column. Check validation rule.(len=128, blank=True)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='fund',
            field=models.CharField(blank=True, default='', help_text='information about research fundings(e.g. JST CREST JPMJCR15E2).', max_length=512),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, help_text='set True when this paper has already published.(default: False)'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('JA', 'Japanese')], help_text="Default language setting for this publication. (choise={'EN' or 'JA'}", max_length=2),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='memo',
            field=models.CharField(blank=True, default='', help_text='note or comment.(blank=True)', max_length=32),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='date and time which this object is updated.This column is automatically filled by django app.(auto_now=True)'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='number',
            field=models.CharField(blank=True, help_text="The '(issue) number' of a journal, magazine, or tech-report,if applicable. Note that this is not the 'article number' assigned by some journals.Before published, ignore this column.(len=128, blank=True)", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='owner',
            field=models.ForeignKey(help_text="user who creates this object.This column is automatically filled by django app.(model='users.User')", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='page',
            field=models.CharField(blank=True, help_text='page number. Before published, ignore this column. Check validation rule.(len=32, blank=True)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='pub_date',
            field=models.DateField(blank=True, default='2000-01-01', help_text='date (year, month, date) on which the book is published. If date-info is no needed, set 01 to the date field.(blank=True) (default: 2000-01-01)', null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="tag for this publication. (model='core.Tag', through='core.TagChain')", through='core.TagChain', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Title of your pubilication (Japanese). Check validation rules.(len=512, blank=True)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='title_ja',
            field=models.CharField(blank=True, default='', help_text='title of your pubilication (Japanese). Check validation rules. (len=512, blank=True)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='url',
            field=models.URLField(blank=True, help_text='An URL to PDF or something. (blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='use_date_info',
            field=models.BooleanField(blank=True, default=False, help_text='if set True, the date will be displayed.(default: False)'),
        ),
        migrations.AlterField(
            model_name='bibtex',
            name='volume',
            field=models.CharField(blank=True, help_text='The volume of a journal or multi-volume book.Before published, ignore this column.(len=128, blank=True)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='abbr',
            field=models.CharField(blank=True, default='', help_text='Book title (Abbreviation).Some words should be replaced based on the local rules.See validation. (len=256, null=True, blank=True)', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, help_text='Miscellaneous extra information.(blank=True)', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text="The publisher's name.(len=256, blank=True)", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='style',
            field=models.CharField(choices=[('Paper', (('JOURNAL', 'Journal'), ('INPROCEEDINGS', 'International Conference'), ('CONF_DOMESTIC', 'Domestic Conference'))), ('Article', (('BOOK', 'Book'), ('NEWS', 'News Paper'), ('MISC', 'Others'), ('ARTICLE', 'Article')))], help_text='Publication Type. See Validation/type for the avaiable choises.(len=32, choice=``core.Book.STYLE_CHOICES``)', max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title (full). Some words should be replaced based on the local rules.See validation rules.(len=256, blank=False)', max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(help_text='Discription of this tag.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='A name of this tag.(len=32, required)', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='A parent tag of this tag entry.(model=Tag, blank=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Tag'),
        ),
    ]
