# Generated by Django 2.2.10 on 2020-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200302_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='style',
            field=models.CharField(choices=[('Paper', (('ARTICLE', 'Journal'), ('INPROCEEDINGS_INTERNATIONAL', 'International Conference'), ('INPROCEEDINGS_DOMESTIC', 'Domestic Conference'))), ('Article', (('BOOK', 'Book'), ('NEWS', 'News Paper'), ('MISC', 'Others')))], help_text='Publication Type. See validation/type for the avaiable choises.(len=32, choice=``core.Book.STYLE_CHOICES``)', max_length=32),
        ),
    ]
